# Load Core Settings
source-file ~/.config/tmux/tmux-core.conf

# Load Keybindings
source-file ~/.config/tmux/tmux-keys.conf

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# (OS X) Fix pbcopy/pbpaste for old tmux versions (pre 2.6)
#set -g default-command "reattach-to-user-namespace -l $SHELL"

# rose pine theme
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'mrjones2014/smart-splits'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

