# rose pine theme
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# smart-splits.nvim (for Neovim navigation)
set -g @smart-splits_move_left_key  'C-h'
set -g @smart-splits_move_down_key  'C-j'
set -g @smart-splits_move_up_key    'C-k'
set -g @smart-splits_move_right_key 'C-l'

set -g @smart-splits_resize_left_key  'M-Left'
set -g @smart-splits_resize_down_key  'M-Down'
set -g @smart-splits_resize_up_key    'M-Up'
set -g @smart-splits_resize_right_key 'M-Right'

# resurrect vim/nvim and pane contents
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# Run the plugin's script
run ~/.config/tmux/plugins/tmux-floax/floax.tmux

run ~/.config/tmux/plugins/tmux-resurrect/resurrect.tmux
